### ISSUE TITLE
Potentially silently ignoring log lines

### ISSUE THREAD

**Issue by me97esn** [KTH/skog#31]
I noticed two things in these code lines
https://github.com/KTH/skog/blob/a98ba52f59808b95d0644407ed7f48070c3b4469/packages/skog/src/index.ts#L23-L27

I see two different problems with this code:
1) There is no "fallback else" statement. If this function is called with something else then `(string, undefined)` or `(any, undefined|string)` it will be silently ignored. Silently ignoring log lines shouldn't be possible IMO, I would much prefer if it threw an error if this is unexpected usage
2) The code is a bit confusing: if arg2 is undefined, the function call will be `fn(arg1, undefined)`, which is exactly the same as `fn(arg1)`. And if these two calls are identical, what's the purpose of these two "if" blocks? Is this on purpose?

**Comment by exacs** [comment]
As strange it might look like, the code is not ignoring any logs if the log function is correctly called.

When you want to write logs you call for example `log.info()`, `log.error()`... The signature of that function is defined here: https://github.com/KTH/skog/blob/a98ba52f59808b95d0644407ed7f48070c3b4469/packages/skog-core/src/log.ts#L15-L19

That interface means that you can call the function with these types:

```
(arg1: Error | Record<string, any>, message?: string): void; // A
(message: string): void;                                     // B
```

It means that you can __only__ call `log.info` in these ways:

a) Just an error as of `A`
b) Just an object as of `A`
c) An error and a string as of `A`
d) An object and a string as of `A`
e) Just a string as of `B`

That function will call the function `logFn` you are showing, passing the "level" and the other two arguments in order

The signature of the two arguments of this function `arg1: Error | string | object, arg2?: unknown` looks strange but, is equivalent to the interface I pasted before. We just need to do this way because JavaScript doesn't allow function polymorphism.

The content of the function ensures that the function is doing the same type-checking as the interface in TypeScript.

```
if (typeof arg1 === "string") {
  // This checks the `B` side (i.e. "only string")
  fn(arg1); 
} else if (typeof arg2 === "undefined" || typeof arg2 === "string") {
  // This checks the `A` side (i.e. arg=object, arg2=undefined|string) 
  fn(arg1, arg2);
}
```



---

So, to answer your questions:

- No, you can not send arbitrary arguments to `skog`, you must pass one of the 5 combinations mentioned before. Otherwise, the library will not do anything.
- Throwing an error from a logging function is very delicate. How are you going to handle such error? How do you log if the logging function fails?
